version: '3.6'

x-shared-environment: &commonEnv
    TZ: "America/Mexico_City"

services:
    cfdiengine:
        container_name: 'cfdiengine'
        build: './DOS/cfdiengine'
        volumes:
          - '${OPM_ROOT}/resources:/resources'
        ports:
          - '10080:10080'
        environment: *commonEnv
        networks:
          - operational_network


networks:
    operational_network:
        name: operational_network
        driver: bridge

volumes:
    rdbms_staging_data:
    rdbms_dos_data:
